from __future__ import annotations

EXAMPLE_QUERIES = (
    {"label": "Extensão por cidade", "query": "extensao por cidade"},
    {"label": "Quantidade por município", "query": "quantidade por municipio"},
    {"label": "Área por bairro", "query": "area por bairro"},
    {"label": "Top 10 categorias", "query": "top 10 categorias"},
)

PLUGIN_HELP_INTENT_TERMS = (
    "ajuda",
    "como",
    "configurar",
    "ensina",
    "explica",
    "explicar",
    "funciona",
    "funcionalidade",
    "o que e",
    "passo a passo",
    "pra que",
    "para que",
    "serve",
    "tutorial",
    "usar",
    "use",
    "what is",
    "what does",
    "how",
    "help",
    "explain",
    "guide",
    "tutorial",
    "step by step",
)

PLUGIN_HELP_SUBJECT_TERMS = (
    "plugin",
    "summarizer",
    "aba",
    "abas",
    "tab",
    "tabs",
    "relatorio",
    "relatorios",
    "reports",
    "resumo",
    "summary",
    "tabela dinamica",
    "pivot",
    "chat",
    "camada",
    "camadas",
    "layer",
    "layers",
    "postgres",
    "postgresql",
    "banco",
    "conexao",
    "conexoes",
    "integracao",
    "integracoes",
    "integration",
    "integrations",
    "connection",
    "connections",
    "modelo",
    "model",
    "dashboard",
    "grafico",
    "graficos",
    "chart",
    "charts",
    "tabela",
    "table",
    "filtro",
    "filtros",
    "filter",
    "filters",
    "exportar",
    "exportacao",
    "export",
    "idioma",
    "language",
    "limpar",
    "gerar",
    "analisar",
    "selecionar",
    "botao",
    "comando",
    "sobre",
    "about",
)

PREVIEW_ROWS = 6
MAX_TABLE_ROWS = 50
REPORTS_FONT_SCALE = 1.0

